### ISSUE TITLE
Versions 0.3.11 and 0.3.12 to be yanked

### ISSUE THREAD

**Issue by VincentJousse** [nomalab/stainless-ffmpeg#50]
Because release 0.3.11 contains API modifications.

See #49  to decide if the API modification should be moved in a minor release or be deleted.

**Comment by Romanelaf** [comment]
Sorry for that. I'm going to rollback to 0.3.10 and put all the changes made after 0.3.10 into a minor release, except for the one that added the stream in `add_input_from_video_decoder`.

**Comment by Romanelaf** [comment]
Ok, I was not used to yanking. I understand that I can fix https://github.com/nomalab/stainless-ffmpeg/issues/49, publish it under 0.3.13 (or 0.4.0 if it's better) and just yank versions 0.3.11 and 0.3.12 to avoid using it in projects dependencies.

**Comment by VincentJousse** [comment]
That’s it !
Take care of breaking changes to decide if you release a minor or a patch version ;)
